### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by christian-rauch**
Minor changes to load dataset paths from the command line and make it work with the examples.

I am unsure about the `labels_maxres(v,u)` which would sometimes returns 24, i.e. the number of clusters and further create an error when accessing arrays, e.g. `b_segm`. I've seen this with the `ball` and the `freiburg3_walking` sequences.

I suspect this comes if the depth is exactly 0, i.e. invalid: https://github.com/raluca-scona/staticfusion/blob/2abd6e57cbee65c22e54b469c178a624fe5d77d2/KMeans.cpp#L265
If this happens, I set the b-weight to 1, i.e. assume that the invalid depth is static. Is there a better way to deal with the invalid depth and the cluster centres?

I also had to enable C++17 to fix an assertion:
http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html

### CODE REVIEW

**Comment by christian-rauch** [comment]
Strange things going on here. I am getting an assertion that points to: http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html.

I can prevent this inside this repo by either enabling C++17 or disabling the AVX instructions (i.e. remove the `-mavx` compiler flag).

However, if I want to use the `sf_lib` externally, the "C++17" solution does not work anymore. I have to disable AVX which theoretically has some performance penalty.

**Comment by raluca-scona** [comment]
Hi, does the app crash on those sequences?

**Comment by christian-rauch** [comment]
> Hi, does the app crash on those sequences?

The process crashes every time an Eigen matrix is accessed. I think it has something to do with how the memory is laid out. Newer C++17 compilers are supposed to fix this memory alignment, but I don't know why this fix won't apply to other projects, e.g. ROS nodes, that import static fusion as a library.

**Comment by raluca-scona** [comment]
I see, I can check my C++ compiler version on my workstation next week. It somehow was not getting any crashes with running it on any sequences :/. The classic "it's working on my computer" excuse :D.

**Comment by raluca-scona** [comment]
Hi, I tested these changes and things seem to work. I do notice that the lack of ``mavx`` makes it run a bit slower.

I am not sure what is the underlying issue with ``labels_maxres(v,u)``, it seems buggy to me. But I will have to investigate this later. 

Thanks for the contribution.

**Pull request merged**
